version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=arvin
      - MONGO_PASSWORD=admin
      - SESSION_SECRET=secret
    command: npm run dev
  nginx:
    ports:
      - "3000:80"
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arvin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=test